### ISSUE TITLE
Issues on versions before `in-20100207-1`

### ISSUE THREAD

**Issue by HappyPlays** [Arc13/IndevProxy#5]
This is probably something to do on my end, but this proxy just isn't working. I put the JVM arguments in the launcher, I installed the script, but the sounds aren't working and saving isn't either. I keep getting this error in the cmd panel repeatendly except the sound that it's attempting to get changes each time: 
"2023-05-22 19:31:46,463 - pid:28804 [I] server.access_log:384 - 127.0.0.1:63097 - GET None:None/resources/newsound/ambient/weather/rain2.ogg - None None - 0 bytes - 10019.34ms
Handling request for: www.minecraft.net/resources/newsound/ambient/weather/rain2.ogg
Resources requested: b'/resources/newsound/ambient/weather/rain2.ogg'
Individual resource passthrough is not currently supported!"
I'm attempting to run in-20091223-2. Hopefully this helps something and please tell me if I'm doing anything wrong.

**Comment by Kuruyia** [comment]
Hi! Sorry for the delay in my response, finally got some time to handle this 😅 

It's an old project so I don't quite remember the compatible versions (should have noted them in the `README` file in hindsight), but based on the few Indev versions that I just tested, indeed works work with yours, `in-20091223-2`.
Saving works but sounds/music doesn't in `in-20100129` and `in-20100201-1`.
Saving and sounds/music works well starting from version `in-20100207-1`.

Please note that the save feature is only supported in versions of the game that could save locally to a file (`in-20091223-2` does not have the "Save file..." button to do this). I remember that the 5 items of the level lists was never supported.
I suspect that older versions of Minecraft expect a different response format than what IndevProxy is replying with. I can't promise to provide a fix, but I might take a look at this.

**Comment by Kuruyia** [comment]
After a bit of investigation, unfortunately this proxy indeed won't cut it for a version this early, sorry 😅
